project_id = "fezpzihnvblzjrdzgioq"

[functions.extract-video-theme]
verify_jwt = false

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
image_transformation = 
  enabled = true

[auth]
enabled = true
port = 54329
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true
enable_anonymous_sign_ups = false

[functions.send-daily-reminders]
verify_jwt = false

[functions.send-weekly-recaps]
verify_jwt = false

[functions.send-leaderboard-alerts]
verify_jwt = false

[functions.process-youtube-video]
verify_jwt = true

[functions.validate-username]
verify_jwt = true

[functions.generate-exercises-from-transcript]
verify_jwt = true

[functions.extract-youtube-transcript]
verify_jwt = false

[functions.generate-level-exercises]
verify_jwt = false

[functions.speech-analyze]
verify_jwt = false

[functions.extract-speaking-phrases]
verify_jwt = false

[functions.backfill-video-durations]
verify_jwt = false
